######################################################################
# Automatically generated by qmake (3.0) ?? ??? 2 13:34:01 2017
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = ex2
INCLUDEPATH += .

# Input
HEADERS += dialogex2.h
FORMS += ex2.ui
SOURCES += dialogex2.cpp ex2.cpp


